The-Imports/graceshopper

server/api/reviews.js

with review routes

---

script/seed.js
server/api/index.js
server/api/orders.js
server/db/models/index.js
server/db/models/order.js

Order api branch

---

server/api/products.js
server/api/reviews.js
server/api/users.js
server/db/models/user.js

fixed some user order review routes

---

server/api/orders.js
server/db/models/product.js
server/db/models/productInstance.js
server/db/models/user.js

with updated routes and models

---

public/index.html
script/seed.js
server/api/category.js
server/api/index.js
server/api/productInstances.js
server/db/models/category.js
server/db/models/index.js
server/db/models/product.js
server/index.js

added category routes

---

client/store/orders.js
client/store/productInstances.js
client/store/products.js
client/store/reviews.js
client/store/users.js

added redux files and one product redux

---

server/index.js

good merge

---

client/components/OrderHistory.js
client/components/UserHome.js
client/components/index.js
client/components/navbar.js
client/index.js
client/routes.js
public/main.html
public/template/main.html
server/api/users.js
server/db/models/order.js
server/index.js

frontend configured

---

client/components/UserHome.js
client/routes.js
client/store/index.js
client/store/products.js

redux added

---

public/template/main.html

added button and table example

---

client/components/SingleUser.js
client/store/users.js
server/api/orders.js
server/db/models/order.js

all the single users

---

server/api/users.js
server/db/models/index.js
server/db/models/order.js

took out parent alias

---

client/components/Checkout.js

added more components

---

client/components/Cart.js
client/store/index.js
client/store/productInstances.js
script/seed.js

redux product instance

---

server/api/index.js
server/index.js

added req.session.cart

---

client/components/user-home.spec.js
script/seed.js
server/api/orders.spec.js

added tests for orders and other changes

---

client/routes.js
server/api/index.js
server/api/session.js
server/index.js

Session branch

---

client/components/navbar.js
server/api/orders.js
server/api/session.js
server/db/models/order.js
server/db/models/product.js
server/db/models/user.js
server/db/models/user.spec.js

session cart added + add to cart route

---

server/api/orders.js
server/api/session.js
server/db/models/product.js
server/db/models/user.js
server/index.js

Cartbranch

---

client/components/Cart.js
client/components/UserHome.js

merged all

---

client/components/Cart.js
client/components/navbar.js

cart works

---

client/components/SingleProduct.js

updated singleproduct

---

client/components/Cart.js
client/components/SingleProduct.js
client/components/navbar.js
client/routes.js
client/store/cart.js
client/store/index.js

add to cart

---

server/api/session.js
server/auth/index.js

checkout route added: api/session/checkout

---

client/components/SingleOrder.js
client/routes.js

some single order progress

---

client/components/AddProduct.js
client/components/SingleOrder.js
client/components/SingleUser.js

single product and single order working no css

---

client/components/Cart.js
client/components/Checkout.js
server/api/session.js
server/auth/index.js
server/db/models/user.js

changed session cart

---

client/components/SingleProduct.js
client/store/reviews.js

singleProductComponent

---

client/components/Cart.js
client/components/OrderHistory.js
client/components/SingleUser.js
client/components/navbar.js

single user linked

---

client/components/AdminDashboard.js
client/components/EditProduct.js
client/components/SingleUser.js
client/routes.js
client/store/index.js
client/store/users.js
server/api/products.js
server/api/session.js
server/db/models/product.js

admin edit pages connected, edit pages in progress

---

client/components/Cart.js
client/components/Checkout.js
client/components/Confirmation.js
client/components/OrderHistory.js
client/components/index.js
client/components/navbar.js
client/routes.js
server/api/orders.js
server/api/session.js
server/db/models/order.js

today's work

---

client/components/AdminDashboard.js
client/components/EditProduct.js
client/components/EditUser.js
client/components/SingleProduct.js
client/components/SingleUser.js
client/store/users.js
server/api/category.js
server/api/users.js

added admin edit functionality

---

client/components/SingleProduct.js
client/components/edit-product.spec.js
client/routes.js
client/store/products.js
server/api/orders.js
server/db/models/user.spec.js

added some stuff

---

client/components/AddProduct.js
server/db/models/product.js

with add product revisions

---

client/components/AddProduct.js
client/components/AdminDashboard.js
client/components/Checkout.js
client/components/Confirmation.js
client/components/EditProduct.js
client/routes.js
server/api/products.js

category stuff added

---

client/components/UserHome.js
package-lock.json
package.json
server/api/sendemail.js

Added email template in our api folder. Set 3 statuses confirmedEmail updatedEmail shippedEmail

---

client/components/SingleProduct.js
client/components/UserHome.js

issues fixed

---

client/components/SingleProduct.js

deploy branch

---

client/components/Checkout.js
client/components/SingleProduct.js

minor fixes

---

client/components/AddProduct.js
client/components/EditUser.js
client/components/SingleUser.js
server/db/models/product.js

took out sportTypes

---

client/store/orders.spec.js

more tests

---

client/components/AuthForm.js
client/components/CategoryProducts.js
client/components/navbar.js

fixed bug with navbar, improved styling for login/signup

---

client/components/AddProduct.js
client/components/AdminDashboard.js
client/components/Cart.js
client/components/ChangePassword.js
client/components/EditUser.js
client/components/OrderHistory.js
client/components/SingleProduct.js
client/components/SingleUser.js
client/store/orders.js

validations

---

client/components/AddProduct.js
client/components/SingleProduct.js
client/components/navbar.js
client/store/cart.js
client/store/productInstances.js
server/api/orders.js
server/api/session.js

updated & fixed
